// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr2nPQBZi-dSclwD6p_b8CCxjO8Iurmy8',
    appId: '1:1084733075471:web:be6c08a3b91dcbd8e1337a',
    messagingSenderId: '1084733075471',
    projectId: 'amiable-vent-364707',
    authDomain: 'amiable-vent-364707.firebaseapp.com',
    storageBucket: 'amiable-vent-364707.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdsU8cZiAg_FoW7I2XZggSSMFnYgJh74g',
    appId: '1:1084733075471:android:3896005662cf8b10e1337a',
    messagingSenderId: '1084733075471',
    projectId: 'amiable-vent-364707',
    storageBucket: 'amiable-vent-364707.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5ZS2oBJa1G7JPuDj6Fj5qFE1oXg4zYl8',
    appId: '1:1084733075471:ios:566c224fb08871b2e1337a',
    messagingSenderId: '1084733075471',
    projectId: 'amiable-vent-364707',
    storageBucket: 'amiable-vent-364707.appspot.com',
    iosClientId:
        '1084733075471-h67ihqtq4cf724jd6h2evbh2lj458uq5.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5ZS2oBJa1G7JPuDj6Fj5qFE1oXg4zYl8',
    appId: '1:1084733075471:ios:566c224fb08871b2e1337a',
    messagingSenderId: '1084733075471',
    projectId: 'amiable-vent-364707',
    storageBucket: 'amiable-vent-364707.appspot.com',
    iosClientId:
        '1084733075471-h67ihqtq4cf724jd6h2evbh2lj458uq5.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatterApp',
  );
}
